# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.6 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-comp-operator
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    integrityshield.io/message: H4sIAAAAAAAAA+1XTW8bNxC9768YyEB6MZWkadNib4oTBD7ENSyhl6AHijurZcwlGZKrVA363zvkiivJWitOCxQwYF4sk/P55pF6OoNFIz1Yo6TYwBqdrCV6CA2C1D5wpXiQRoOp056paykkV/AMfGetcQGr6OV7m+IsWV2Y1irJtUD4zaLjwTig83jUcs1X5CNU5wP5TYszcrqswWOAYGCCujZO4ARk+EGpXESffBur97kyAWmbh5hDzxtZB/hp+hqoG4efO+mwmhbcyt/76sptj1OKotk2PevLaVGHqTTP1y+LW6mrEq6TadFi4BUPvCwANG8xx2CCGmS5HDrkWpuQgPLRFh6Qi9rSFXeVL+Hqcr6A+TX8+uIF+/nVA/0FD7gyjoZVwsUM5ig6J8MGZt6j99GKqqpg1oWGrP5KxT00tNHBGZUCsx/HQvvzePQLDVoHqTvTefhgtCQwpF4V3qKIMDiKWMmUeSZCmoGM023prJKeLxUS1jVXHotcFwtI3KHetkAyMMtPKMJbrCUliEHSflzfPdzs2A+Ziq/lqnOpwO3Es8X+5PPqGXAweqb9YJC7zuve7uEMvkii9JIYTVfHyapCDcvNsQc5gOUuztIe1kfpMF7WsCmhkatm76DH6y6OebHUQH85FxtLDbUEVsPXeGAGJ2Afg38P3EOQrwg0b7m4G34c4kOo4zB9vNdsV/NjIMXwYeVMZ58IEjvLmPipMA5N/NM+v5c1+Vvj/QGAp+ZwPI++hf1Xesw2cfME1fbX3QHmFbhbYRiY7sdsEmkfKZ99t/TCSTt8hYyB8cTm9UuubMPv4/R8DMVTozgeyf9HadGQpEFVwoQk1WTEYKvLrhXXM2udWXMyJrFhWhqo+I9deNO52AJJONJ3g6W/1/RqrO2Wu1sMxArqmzH2r7VgDBB339C/Ud4cq8Jlf8JG1aHN/jdY7wnJvDvulEkzJL/pVJwe9ZDexJI+WX+i/oIubWR0ug/stHodku0u3S7PN5E6wvYblY0gm5obEdunMcrc3Wahl66SexKcATE0dKRiJwvXYSZxSK/Ah/5nyMUd19maSxV16S7sHBXBaFwflNgtmnd/WkdCeJcqJvt6i/Q4rVFXxp0PD0QJl/oc6HJ0Uad/nAw/VSZ//F38Awv6+ox8DQAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIVVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvRzkrQy80bmZPR1Jidm1kUmgyZm9mUmJaL1BKc2Z5TgpSdWhCZUkyaXM1V1FKM3B3NlE0RHZVOEI1UXFvZjloZjQ4dWFSS3Q4OHFXU1ZTbEZVYnorUVcxTmNDRUkvajZHCnhFeU1XL3V1eG5DQlVTdGpWa2FZQ2krdkxzL1FvUENRWnJxOEd4cjJJbjdCcVpmT1JCdysvZUZUUFVNUEFMUDIKYTR2RERweFl2R3hXSU5ITFJ3Tm80Z3ovMkx6c05aUjB6YVRmV2VpZHM4a2tJWlhUengyWGQvcDR2eXpIVjN4OQpSNGpXQldXSXpyYUx3bUMrWm9RajVQWTFTR3FFcWYrVnRjc2FrZFdxZzg2ZmZCU0U5c3Zpc2RCSG5paklYVXgyCmJmYWNvVjRwM0srcHMveFZsREl3dEdPNCtUL205akNqckNMK3dVdWtlREtMNk40ekUyVzlUdFRGbkk5VXQ5eDUKNEhCNjJ1bVpCcng4TWFRSlpxWFhTYTVDb3JUSTZsbXZmaDF1cW5oblNvc1d1bndoRXVKdWlILzBvWmgwWUdpNApKS3ZoUjBJNklrb0pBRjhCTUtCRDk4bFhTdHJXOE1nZlVUcHVPYndqUnplMTFVWFNZTjhLbXR5eGU5YW84QnQzCitQMGpnTFdmOGdYT2cremtFYVBFZ2dGT010bzRRRnZJbHBDanh5bz0KPTQ1SmUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-ns
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-compliance
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-operator-group
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  targetNamespaces:
                    - openshift-compliance
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-subscription
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  installPlanApproval: Automatic
                  name: compliance-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-comp-operator
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA+1XTW8bNxC9768YyEB6MZWkadNib4oTBD7ENSyhl6AHijurZcwlGZKrVA363zvkiivJWitOCxQwYF4sk/P55pF6OoNFIz1Yo6TYwBqdrCV6CA2C1D5wpXiQRoOp056paykkV/AMfGetcQGr6OV7m+IsWV2Y1irJtUD4zaLjwTig83jUcs1X5CNU5wP5TYszcrqswWOAYGCCujZO4ARk+EGpXESffBur97kyAWmbh5hDzxtZB/hp+hqoG4efO+mwmhbcyt/76sptj1OKotk2PevLaVGHqTTP1y+LW6mrEq6TadFi4BUPvCwANG8xx2CCGmS5HDrkWpuQgPLRFh6Qi9rSFXeVL+Hqcr6A+TX8+uIF+/nVA/0FD7gyjoZVwsUM5ig6J8MGZt6j99GKqqpg1oWGrP5KxT00tNHBGZUCsx/HQvvzePQLDVoHqTvTefhgtCQwpF4V3qKIMDiKWMmUeSZCmoGM023prJKeLxUS1jVXHotcFwtI3KHetkAyMMtPKMJbrCUliEHSflzfPdzs2A+Ziq/lqnOpwO3Es8X+5PPqGXAweqb9YJC7zuve7uEMvkii9JIYTVfHyapCDcvNsQc5gOUuztIe1kfpMF7WsCmhkatm76DH6y6OebHUQH85FxtLDbUEVsPXeGAGJ2Afg38P3EOQrwg0b7m4G34c4kOo4zB9vNdsV/NjIMXwYeVMZ58IEjvLmPipMA5N/NM+v5c1+Vvj/QGAp+ZwPI++hf1Xesw2cfME1fbX3QHmFbhbYRiY7sdsEmkfKZ99t/TCSTt8hYyB8cTm9UuubMPv4/R8DMVTozgeyf9HadGQpEFVwoQk1WTEYKvLrhXXM2udWXMyJrFhWhqo+I9deNO52AJJONJ3g6W/1/RqrO2Wu1sMxArqmzH2r7VgDBB339C/Ud4cq8Jlf8JG1aHN/jdY7wnJvDvulEkzJL/pVJwe9ZDexJI+WX+i/oIubWR0ug/stHodku0u3S7PN5E6wvYblY0gm5obEdunMcrc3Wahl66SexKcATE0dKRiJwvXYSZxSK/Ah/5nyMUd19maSxV16S7sHBXBaFwflNgtmnd/WkdCeJcqJvt6i/Q4rVFXxp0PD0QJl/oc6HJ0Uad/nAw/VSZ//F38Awv6+ox8DQAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIVVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvRzkrQy80bmZPR1Jidm1kUmgyZm9mUmJaL1BKc2Z5TgpSdWhCZUkyaXM1V1FKM3B3NlE0RHZVOEI1UXFvZjloZjQ4dWFSS3Q4OHFXU1ZTbEZVYnorUVcxTmNDRUkvajZHCnhFeU1XL3V1eG5DQlVTdGpWa2FZQ2krdkxzL1FvUENRWnJxOEd4cjJJbjdCcVpmT1JCdysvZUZUUFVNUEFMUDIKYTR2RERweFl2R3hXSU5ITFJ3Tm80Z3ovMkx6c05aUjB6YVRmV2VpZHM4a2tJWlhUengyWGQvcDR2eXpIVjN4OQpSNGpXQldXSXpyYUx3bUMrWm9RajVQWTFTR3FFcWYrVnRjc2FrZFdxZzg2ZmZCU0U5c3Zpc2RCSG5paklYVXgyCmJmYWNvVjRwM0srcHMveFZsREl3dEdPNCtUL205akNqckNMK3dVdWtlREtMNk40ekUyVzlUdFRGbkk5VXQ5eDUKNEhCNjJ1bVpCcng4TWFRSlpxWFhTYTVDb3JUSTZsbXZmaDF1cW5oblNvc1d1bndoRXVKdWlILzBvWmgwWUdpNApKS3ZoUjBJNklrb0pBRjhCTUtCRDk4bFhTdHJXOE1nZlVUcHVPYndqUnplMTFVWFNZTjhLbXR5eGU5YW84QnQzCitQMGpnTFdmOGdYT2cremtFYVBFZ2dGT010bzRRRnZJbHBDanh5bz0KPTQ1SmUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
placementRef:
  name: placement-policy-comp-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-comp-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-comp-operator
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA+1XTW8bNxC9768YyEB6MZWkadNib4oTBD7ENSyhl6AHijurZcwlGZKrVA363zvkiivJWitOCxQwYF4sk/P55pF6OoNFIz1Yo6TYwBqdrCV6CA2C1D5wpXiQRoOp056paykkV/AMfGetcQGr6OV7m+IsWV2Y1irJtUD4zaLjwTig83jUcs1X5CNU5wP5TYszcrqswWOAYGCCujZO4ARk+EGpXESffBur97kyAWmbh5hDzxtZB/hp+hqoG4efO+mwmhbcyt/76sptj1OKotk2PevLaVGHqTTP1y+LW6mrEq6TadFi4BUPvCwANG8xx2CCGmS5HDrkWpuQgPLRFh6Qi9rSFXeVL+Hqcr6A+TX8+uIF+/nVA/0FD7gyjoZVwsUM5ig6J8MGZt6j99GKqqpg1oWGrP5KxT00tNHBGZUCsx/HQvvzePQLDVoHqTvTefhgtCQwpF4V3qKIMDiKWMmUeSZCmoGM023prJKeLxUS1jVXHotcFwtI3KHetkAyMMtPKMJbrCUliEHSflzfPdzs2A+Ziq/lqnOpwO3Es8X+5PPqGXAweqb9YJC7zuve7uEMvkii9JIYTVfHyapCDcvNsQc5gOUuztIe1kfpMF7WsCmhkatm76DH6y6OebHUQH85FxtLDbUEVsPXeGAGJ2Afg38P3EOQrwg0b7m4G34c4kOo4zB9vNdsV/NjIMXwYeVMZ58IEjvLmPipMA5N/NM+v5c1+Vvj/QGAp+ZwPI++hf1Xesw2cfME1fbX3QHmFbhbYRiY7sdsEmkfKZ99t/TCSTt8hYyB8cTm9UuubMPv4/R8DMVTozgeyf9HadGQpEFVwoQk1WTEYKvLrhXXM2udWXMyJrFhWhqo+I9deNO52AJJONJ3g6W/1/RqrO2Wu1sMxArqmzH2r7VgDBB339C/Ud4cq8Jlf8JG1aHN/jdY7wnJvDvulEkzJL/pVJwe9ZDexJI+WX+i/oIubWR0ug/stHodku0u3S7PN5E6wvYblY0gm5obEdunMcrc3Wahl66SexKcATE0dKRiJwvXYSZxSK/Ah/5nyMUd19maSxV16S7sHBXBaFwflNgtmnd/WkdCeJcqJvt6i/Q4rVFXxp0PD0QJl/oc6HJ0Uad/nAw/VSZ//F38Awv6+ox8DQAA
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIVVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvRzkrQy80bmZPR1Jidm1kUmgyZm9mUmJaL1BKc2Z5TgpSdWhCZUkyaXM1V1FKM3B3NlE0RHZVOEI1UXFvZjloZjQ4dWFSS3Q4OHFXU1ZTbEZVYnorUVcxTmNDRUkvajZHCnhFeU1XL3V1eG5DQlVTdGpWa2FZQ2krdkxzL1FvUENRWnJxOEd4cjJJbjdCcVpmT1JCdysvZUZUUFVNUEFMUDIKYTR2RERweFl2R3hXSU5ITFJ3Tm80Z3ovMkx6c05aUjB6YVRmV2VpZHM4a2tJWlhUengyWGQvcDR2eXpIVjN4OQpSNGpXQldXSXpyYUx3bUMrWm9RajVQWTFTR3FFcWYrVnRjc2FrZFdxZzg2ZmZCU0U5c3Zpc2RCSG5paklYVXgyCmJmYWNvVjRwM0srcHMveFZsREl3dEdPNCtUL205akNqckNMK3dVdWtlREtMNk40ekUyVzlUdFRGbkk5VXQ5eDUKNEhCNjJ1bVpCcng4TWFRSlpxWFhTYTVDb3JUSTZsbXZmaDF1cW5oblNvc1d1bndoRXVKdWlILzBvWmgwWUdpNApKS3ZoUjBJNklrb0pBRjhCTUtCRDk4bFhTdHJXOE1nZlVUcHVPYndqUnplMTFVWFNZTjhLbXR5eGU5YW84QnQzCitQMGpnTFdmOGdYT2cremtFYVBFZ2dGT010bzRRRnZJbHBDanh5bz0KPTQ1SmUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
