apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-limitmemory
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
<<<<<<< HEAD:stable/CM-Configuration-Management/policy-limitmemory.yaml
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    integrityshield.io/message: H4sIAAAAAAAAA5VVXW/aMBR9z6+4Ym9TzVqmTlPe2m6aKq1TRau9TH24JBfq4diZ7URF0/77rh0CCQRK/QS+3+ecXGMpf5J10ugUSqNkthqbkrTIVOU8WVGgxgUVpP1Ymg/1RbKUOk/hPromBXnM0WOaAGgsqM0hlCykL6gwdsUm1Np49FzEBU84oZLzqHO0uUvhx+3DIzzcw+fzc3H58cT4DD0tjJXECW7u4MbouVxUNjYBdxvXU7MZ7a1RMZeYwDU6UlJTP23iSsrCfJbjchnvrjIfoZV6bmzBtlw6nCliCOeoHCVtdeGpKBU3vUZIgJn9psx/obnUMiaJ9+HgWzlrAxvuek2viWw9uoS2Z59Yi3pBgl6QW6aNZzt+ew7CAO/AP9Pu4DF+vBcE0oGpyVqZ56RhtmpiLWXspxdQouX+eGyoUVUEXOBApnGnN0ecUvpVCsGpKnbGdSVm9ECKCTC2OxMAvTDMOQPya7SsZiTej556dqk39pzmWCnfc2hY3WW7PQIywwaJOqPHVclZCqb0GWvqucERcQyJpCOBvhS+BzangU3mJFILzUcLlWMJ7UUNyaOLW4CzaDQiokj2/HZF0p4Y44YsAZU1ksPmprHQdQqXF5M7ecBrnWRKfypyJ+SaXH46mMtHcvhL8sh7wCZCiOTNn+V6lSrWWri95r+s6IGlOmssYmC5lm30lOadLdzeDoW05G8KT6v4FXP/36ypypR/le5I74mrovwiXeLY4t+U2m6ZbZVXMdpD9ZW+BjCNow28UsfwaSW6rsEk57Lzdgngt8lX/BaMHm1Fo6SriOZlyW92Qq9qlCrs/W3a/nYp0GfPX194rTm3LRWK/V0Sa5F0La3RoeUzYAR4eXMo3OqzZu25Zt/Uo6d/yX9SZJc50wcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIWVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTXRmQy85dlcxUUFsWGVOQ3RQdm9kZS9NdWJXTHo0SApQVTIySyswZmNTNVpYYTZ6WEFwRUZSR3h4ck5STDRGWjM1MWszTnNSNktLb3ltUlkzRVdDaGVKN2xyaUpLZ3Z2CllEZGptT2RPbkZpN1AySm5pU0VhWklEbnZoUllpdGlRMHliUjZpcEU1WFRqYnFhOUJtY3VjUWpoQkNZRUNrb3EKVHJvNmVKQ2lSV0IxdjF3d0FjVnMxdFBINTlBeDJsclAxRWhuREo4enFwSVAwQWx0YUFaQnRxMlE1TlVIYlNGVQpiTzhPYXdiUG0zMWo5aUNWZXduYTErWldVYnN3TnIvS2pTUmh0cnpkYkNVMWFwUTFMS1FmQTROMG1XU0tZK0JpCnJGWXdMNm5DaWJSVHpCMVp4WENUWVh2RTN0dVY4aFViR2xHdlIrTzFIRGErSTh6Qk1EUlYvZXJzTEhRMFBQaEEKZ2NMY2dQdTFkSnFqNXBoZHU3T01GSGlPdm1LSldhT3pXdTRycnJUdzY1Ukt1YW8vYWNoeDcyakpERXF3dGNHRgorbUNFU1BndVNvZ2pIUHhpcGlzVXI2VGNZa0loRm9acUxjdVlrbDhRc2pGRjBhOCtMT1dKZnBwdHVvSlJHSFQ1CmV3Ykhxa3dkSzNPbmQ5azIvSCtWT09UZkpMTjdLdENSYXV4N0hJRT0KPW9HUVUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
=======
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-6 Resource Availability
>>>>>>> upstream/master:stable/SC-System-and-Communications-Protection/policy-limitmemory.yaml
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-limitrange-example
        spec:
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: medium
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange # limit memory usage
                metadata:
                  name: mem-limit-range
                spec:
                  limits:
                    - default:
                        memory: 512Mi
                      defaultRequest:
                        memory: 256Mi
                      type: Container
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-limitmemory
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA5VVXW/aMBR9z6+4Ym9TzVqmTlPe2m6aKq1TRau9TH24JBfq4diZ7URF0/77rh0CCQRK/QS+3+ecXGMpf5J10ugUSqNkthqbkrTIVOU8WVGgxgUVpP1Ymg/1RbKUOk/hPromBXnM0WOaAGgsqM0hlCykL6gwdsUm1Np49FzEBU84oZLzqHO0uUvhx+3DIzzcw+fzc3H58cT4DD0tjJXECW7u4MbouVxUNjYBdxvXU7MZ7a1RMZeYwDU6UlJTP23iSsrCfJbjchnvrjIfoZV6bmzBtlw6nCliCOeoHCVtdeGpKBU3vUZIgJn9psx/obnUMiaJ9+HgWzlrAxvuek2viWw9uoS2Z59Yi3pBgl6QW6aNZzt+ew7CAO/AP9Pu4DF+vBcE0oGpyVqZ56RhtmpiLWXspxdQouX+eGyoUVUEXOBApnGnN0ecUvpVCsGpKnbGdSVm9ECKCTC2OxMAvTDMOQPya7SsZiTej556dqk39pzmWCnfc2hY3WW7PQIywwaJOqPHVclZCqb0GWvqucERcQyJpCOBvhS+BzangU3mJFILzUcLlWMJ7UUNyaOLW4CzaDQiokj2/HZF0p4Y44YsAZU1ksPmprHQdQqXF5M7ecBrnWRKfypyJ+SaXH46mMtHcvhL8sh7wCZCiOTNn+V6lSrWWri95r+s6IGlOmssYmC5lm30lOadLdzeDoW05G8KT6v4FXP/36ypypR/le5I74mrovwiXeLY4t+U2m6ZbZVXMdpD9ZW+BjCNow28UsfwaSW6rsEk57Lzdgngt8lX/BaMHm1Fo6SriOZlyW92Qq9qlCrs/W3a/nYp0GfPX194rTm3LRWK/V0Sa5F0La3RoeUzYAR4eXMo3OqzZu25Zt/Uo6d/yX9SZJc50wcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIWVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTXRmQy85dlcxUUFsWGVOQ3RQdm9kZS9NdWJXTHo0SApQVTIySyswZmNTNVpYYTZ6WEFwRUZSR3h4ck5STDRGWjM1MWszTnNSNktLb3ltUlkzRVdDaGVKN2xyaUpLZ3Z2CllEZGptT2RPbkZpN1AySm5pU0VhWklEbnZoUllpdGlRMHliUjZpcEU1WFRqYnFhOUJtY3VjUWpoQkNZRUNrb3EKVHJvNmVKQ2lSV0IxdjF3d0FjVnMxdFBINTlBeDJsclAxRWhuREo4enFwSVAwQWx0YUFaQnRxMlE1TlVIYlNGVQpiTzhPYXdiUG0zMWo5aUNWZXduYTErWldVYnN3TnIvS2pTUmh0cnpkYkNVMWFwUTFMS1FmQTROMG1XU0tZK0JpCnJGWXdMNm5DaWJSVHpCMVp4WENUWVh2RTN0dVY4aFViR2xHdlIrTzFIRGErSTh6Qk1EUlYvZXJzTEhRMFBQaEEKZ2NMY2dQdTFkSnFqNXBoZHU3T01GSGlPdm1LSldhT3pXdTRycnJUdzY1Ukt1YW8vYWNoeDcyakpERXF3dGNHRgorbUNFU1BndVNvZ2pIUHhpcGlzVXI2VGNZa0loRm9acUxjdVlrbDhRc2pGRjBhOCtMT1dKZnBwdHVvSlJHSFQ1CmV3Ykhxa3dkSzNPbmQ5azIvSCtWT09UZkpMTjdLdENSYXV4N0hJRT0KPW9HUVUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
placementRef:
  name: placement-policy-limitmemory
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-limitmemory
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-limitmemory
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA5VVXW/aMBR9z6+4Ym9TzVqmTlPe2m6aKq1TRau9TH24JBfq4diZ7URF0/77rh0CCQRK/QS+3+ecXGMpf5J10ugUSqNkthqbkrTIVOU8WVGgxgUVpP1Ymg/1RbKUOk/hPromBXnM0WOaAGgsqM0hlCykL6gwdsUm1Np49FzEBU84oZLzqHO0uUvhx+3DIzzcw+fzc3H58cT4DD0tjJXECW7u4MbouVxUNjYBdxvXU7MZ7a1RMZeYwDU6UlJTP23iSsrCfJbjchnvrjIfoZV6bmzBtlw6nCliCOeoHCVtdeGpKBU3vUZIgJn9psx/obnUMiaJ9+HgWzlrAxvuek2viWw9uoS2Z59Yi3pBgl6QW6aNZzt+ew7CAO/AP9Pu4DF+vBcE0oGpyVqZ56RhtmpiLWXspxdQouX+eGyoUVUEXOBApnGnN0ecUvpVCsGpKnbGdSVm9ECKCTC2OxMAvTDMOQPya7SsZiTej556dqk39pzmWCnfc2hY3WW7PQIywwaJOqPHVclZCqb0GWvqucERcQyJpCOBvhS+BzangU3mJFILzUcLlWMJ7UUNyaOLW4CzaDQiokj2/HZF0p4Y44YsAZU1ksPmprHQdQqXF5M7ecBrnWRKfypyJ+SaXH46mMtHcvhL8sh7wCZCiOTNn+V6lSrWWri95r+s6IGlOmssYmC5lm30lOadLdzeDoW05G8KT6v4FXP/36ypypR/le5I74mrovwiXeLY4t+U2m6ZbZVXMdpD9ZW+BjCNow28UsfwaSW6rsEk57Lzdgngt8lX/BaMHm1Fo6SriOZlyW92Qq9qlCrs/W3a/nYp0GfPX194rTm3LRWK/V0Sa5F0La3RoeUzYAR4eXMo3OqzZu25Zt/Uo6d/yX9SZJc50wcAAA==
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL1NIWVdISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTXRmQy85dlcxUUFsWGVOQ3RQdm9kZS9NdWJXTHo0SApQVTIySyswZmNTNVpYYTZ6WEFwRUZSR3h4ck5STDRGWjM1MWszTnNSNktLb3ltUlkzRVdDaGVKN2xyaUpLZ3Z2CllEZGptT2RPbkZpN1AySm5pU0VhWklEbnZoUllpdGlRMHliUjZpcEU1WFRqYnFhOUJtY3VjUWpoQkNZRUNrb3EKVHJvNmVKQ2lSV0IxdjF3d0FjVnMxdFBINTlBeDJsclAxRWhuREo4enFwSVAwQWx0YUFaQnRxMlE1TlVIYlNGVQpiTzhPYXdiUG0zMWo5aUNWZXduYTErWldVYnN3TnIvS2pTUmh0cnpkYkNVMWFwUTFMS1FmQTROMG1XU0tZK0JpCnJGWXdMNm5DaWJSVHpCMVp4WENUWVh2RTN0dVY4aFViR2xHdlIrTzFIRGErSTh6Qk1EUlYvZXJzTEhRMFBQaEEKZ2NMY2dQdTFkSnFqNXBoZHU3T01GSGlPdm1LSldhT3pXdTRycnJUdzY1Ukt1YW8vYWNoeDcyakpERXF3dGNHRgorbUNFU1BndVNvZ2pIUHhpcGlzVXI2VGNZa0loRm9acUxjdVlrbDhRc2pGRjBhOCtMT1dKZnBwdHVvSlJHSFQ1CmV3Ykhxa3dkSzNPbmQ5azIvSCtWT09UZkpMTjdLdENSYXV4N0hJRT0KPW9HUVUKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
