# This policy checks if Integrity Shield has denied one or
# more requests on the managed clusters.
#
# "inform" This policy will show "Not compliant" on UI when something was denied.

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-integrity-shield-events
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
    integrityshield.io/message: H4sIAAAAAAAAA51VPW/bMBDd9SsO8haEbooiQKEtcYMiQ4LAdrsEGWjxZLGmSJWk5BhF/3tPlKXIjmu75SSRd+8+3vFxBPNcOiiNkukG0hzTlQOZwb32uLTSb2CWS1QCcu5AoJYowGgEY6MRFMYiWPxZofOOtsHnCAXXfElWqaqcR+vG0YhMY6kzY4t4J9xaKgUuN2uIH42H1BSlklz7uMH6dg/rHDU4U6DPpV7Cuk9hHEW8lN8JXRqdbOHGpkTNtmFZm0aB2o+l+VB/jFZSiwSegmlEkFxwz5MIQPMCOwwmu7qZC3UzrAnCkRnX2njuKaBrvOCMqM5zLbgVLoHH+9kcZk/w+eqKXX860z/llIyxEglg8gATozO5rGxIAh5603PRjPbWqIDFruEmTdE5mBJ3VqahLiCKYJJzvcTIlZg2dVryFzKEvAlWCbRU0pmQji8UUlszrhxGXRbMIzFJyW87xcAsfmDqv2AmtQwgYb9Z/8xj59jyudOTLbmdxZDkbh0nm4tCuiaX3qNrQ7f+2g4YteO8oLtRo7VS0KjCYvPegxyg5JYq2uYxgHc0bk1CCSiz3kvblTzFGSpqpLHDnIAQqV2CCnuOL+KXnSN87Y9W1QLZRXwJcdNhKjnzbNe8pWmfvm6x/oamON+UhFkQR3Qrcl7jjiUcIfwQ8QNad+m9q7v5Hq5DxPaw+9d0f/Wkt5w3UxXueFtR0/5swyy6Sr0PfMx/GlySRqE2EWPsvxVKEc3N7i39kuwd0KpFe8JOaFbZIU0xGwhdt3vKveOgT2haqYZmquurNVWZ0FfpjtQUuSpMQSCCnauzfdi3u/EW8WQf33X+RI4H+h7KPPBAnNu3TjK28UihhBzMIwN6FnxFMhzPbYXxdsh8GL9W1MVkz/Wm5lI1UvsGuysEBfdpfvda0ty64egz+LVCUhPUtbRGN+lfAnWD9JJc6ZW/hJqrqnlgnmOBdfzyO/oD1P2FnRMIAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL0VOa1dISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTm5qQy80OWVUUTZZRnIwemF2VEZFc0lNU1owZHA2cwo4Y1dHVDhRdUdUbmd5MmQwc1BSQkdWVXpDVEdqcXRrOFkrTHR5eWFlb1hmU1J4RUJ4R0VnaWF1cTJvMjlzRXRDCnNUayszcXpCVTJUZ0RWR043ZWljRmxjZVpLVmEyL3BqdjdJWStzSjdvNEw0YmEyQW95ZkU0WmNWR1ZSZmVGamEKc2ttTHNKSFV6RGZNQlRSSEx6MDJpczV5RUdIeU1LWFRzVDZjWWJTV2wyNENJdzVSU0M1TytSTHNXSU5XV1czRQpkMnl3OElaK3QxYmZNRitSSzdUVmtJM1lTQTU3SWtJQzBJdTRmZmRSYi9vL085UWFqVHpzblpkU2sxUmtWY2huCjJvemp5QmIyS3V0aktMSEtRbXRMNjhaelRRZ2Rydjl2QStMeUNPNmgyeFB3em54bkNUOXBXNkZ2aDUwVTFIUlMKUm1mUU9kdXpEdHRINjl2ZSs1a2x3eDJLSDFLS1VxWU03N3Zwc1JhbllxYnE0b3pieEx2blJ0cWJOZGhWNDc5dQpYSGg2c3k3USt5Q0NjdzhlTE45MFdhZThqY1h1VzBrczhUeDhuZVhsaUJ4LzlKUWFWK1JOcXFvRFFFeTIvMytwCkhIVW1aT3ZkVkFmS3Ayb3hQa2VVaUNmTEhrc3cyMFVYcCtMN01qTT0KPUltaHMKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-integrity-shield-admission
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: low
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-*", "openshift-*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Event
                metadata:
                  annotations:
                    integrityshield.io/eventType: verify-result
                    integrityshield.io/eventResult: deny
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-integrity-shield-events
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA51VPW/bMBDd9SsO8haEbooiQKEtcYMiQ4LAdrsEGWjxZLGmSJWk5BhF/3tPlKXIjmu75SSRd+8+3vFxBPNcOiiNkukG0hzTlQOZwb32uLTSb2CWS1QCcu5AoJYowGgEY6MRFMYiWPxZofOOtsHnCAXXfElWqaqcR+vG0YhMY6kzY4t4J9xaKgUuN2uIH42H1BSlklz7uMH6dg/rHDU4U6DPpV7Cuk9hHEW8lN8JXRqdbOHGpkTNtmFZm0aB2o+l+VB/jFZSiwSegmlEkFxwz5MIQPMCOwwmu7qZC3UzrAnCkRnX2njuKaBrvOCMqM5zLbgVLoHH+9kcZk/w+eqKXX860z/llIyxEglg8gATozO5rGxIAh5603PRjPbWqIDFruEmTdE5mBJ3VqahLiCKYJJzvcTIlZg2dVryFzKEvAlWCbRU0pmQji8UUlszrhxGXRbMIzFJyW87xcAsfmDqv2AmtQwgYb9Z/8xj59jyudOTLbmdxZDkbh0nm4tCuiaX3qNrQ7f+2g4YteO8oLtRo7VS0KjCYvPegxyg5JYq2uYxgHc0bk1CCSiz3kvblTzFGSpqpLHDnIAQqV2CCnuOL+KXnSN87Y9W1QLZRXwJcdNhKjnzbNe8pWmfvm6x/oamON+UhFkQR3Qrcl7jjiUcIfwQ8QNad+m9q7v5Hq5DxPaw+9d0f/Wkt5w3UxXueFtR0/5swyy6Sr0PfMx/GlySRqE2EWPsvxVKEc3N7i39kuwd0KpFe8JOaFbZIU0xGwhdt3vKveOgT2haqYZmquurNVWZ0FfpjtQUuSpMQSCCnauzfdi3u/EW8WQf33X+RI4H+h7KPPBAnNu3TjK28UihhBzMIwN6FnxFMhzPbYXxdsh8GL9W1MVkz/Wm5lI1UvsGuysEBfdpfvda0ty64egz+LVCUhPUtbRGN+lfAnWD9JJc6ZW/hJqrqnlgnmOBdfzyO/oD1P2FnRMIAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL0VOa1dISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTm5qQy80OWVUUTZZRnIwemF2VEZFc0lNU1owZHA2cwo4Y1dHVDhRdUdUbmd5MmQwc1BSQkdWVXpDVEdqcXRrOFkrTHR5eWFlb1hmU1J4RUJ4R0VnaWF1cTJvMjlzRXRDCnNUayszcXpCVTJUZ0RWR043ZWljRmxjZVpLVmEyL3BqdjdJWStzSjdvNEw0YmEyQW95ZkU0WmNWR1ZSZmVGamEKc2ttTHNKSFV6RGZNQlRSSEx6MDJpczV5RUdIeU1LWFRzVDZjWWJTV2wyNENJdzVSU0M1TytSTHNXSU5XV1czRQpkMnl3OElaK3QxYmZNRitSSzdUVmtJM1lTQTU3SWtJQzBJdTRmZmRSYi9vL085UWFqVHpzblpkU2sxUmtWY2huCjJvemp5QmIyS3V0aktMSEtRbXRMNjhaelRRZ2Rydjl2QStMeUNPNmgyeFB3em54bkNUOXBXNkZ2aDUwVTFIUlMKUm1mUU9kdXpEdHRINjl2ZSs1a2x3eDJLSDFLS1VxWU03N3Zwc1JhbllxYnE0b3pieEx2blJ0cWJOZGhWNDc5dQpYSGg2c3k3USt5Q0NjdzhlTE45MFdhZThqY1h1VzBrczhUeDhuZVhsaUJ4LzlKUWFWK1JOcXFvRFFFeTIvMytwCkhIVW1aT3ZkVkFmS3Ayb3hQa2VVaUNmTEhrc3cyMFVYcCtMN01qTT0KPUltaHMKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
placementRef:
  name: placement-policy-integrity-shield-events
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-integrity-shield-events
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-integrity-shield-events
  annotations:
    integrityshield.io/message: H4sIAAAAAAAAA51VPW/bMBDd9SsO8haEbooiQKEtcYMiQ4LAdrsEGWjxZLGmSJWk5BhF/3tPlKXIjmu75SSRd+8+3vFxBPNcOiiNkukG0hzTlQOZwb32uLTSb2CWS1QCcu5AoJYowGgEY6MRFMYiWPxZofOOtsHnCAXXfElWqaqcR+vG0YhMY6kzY4t4J9xaKgUuN2uIH42H1BSlklz7uMH6dg/rHDU4U6DPpV7Cuk9hHEW8lN8JXRqdbOHGpkTNtmFZm0aB2o+l+VB/jFZSiwSegmlEkFxwz5MIQPMCOwwmu7qZC3UzrAnCkRnX2njuKaBrvOCMqM5zLbgVLoHH+9kcZk/w+eqKXX860z/llIyxEglg8gATozO5rGxIAh5603PRjPbWqIDFruEmTdE5mBJ3VqahLiCKYJJzvcTIlZg2dVryFzKEvAlWCbRU0pmQji8UUlszrhxGXRbMIzFJyW87xcAsfmDqv2AmtQwgYb9Z/8xj59jyudOTLbmdxZDkbh0nm4tCuiaX3qNrQ7f+2g4YteO8oLtRo7VS0KjCYvPegxyg5JYq2uYxgHc0bk1CCSiz3kvblTzFGSpqpLHDnIAQqV2CCnuOL+KXnSN87Y9W1QLZRXwJcdNhKjnzbNe8pWmfvm6x/oamON+UhFkQR3Qrcl7jjiUcIfwQ8QNad+m9q7v5Hq5DxPaw+9d0f/Wkt5w3UxXueFtR0/5swyy6Sr0PfMx/GlySRqE2EWPsvxVKEc3N7i39kuwd0KpFe8JOaFbZIU0xGwhdt3vKveOgT2haqYZmquurNVWZ0FfpjtQUuSpMQSCCnauzfdi3u/EW8WQf33X+RI4H+h7KPPBAnNu3TjK28UihhBzMIwN6FnxFMhzPbYXxdsh8GL9W1MVkz/Wm5lI1UvsGuysEBfdpfvda0ty64egz+LVCUhPUtbRGN+lfAnWD9JJc6ZW/hJqrqnlgnmOBdfzyO/oD1P2FnRMIAAA=
    integrityshield.io/signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0KCmlRSEtCQUFCQ2dBMEZpRUVDOFZXV2MvQlNhOXE3cENPcCtvcnBLeFFhdndGQW1BL0VOa1dISE5wWjI1bGNrQmwKYm5SbGNuQnlhWE5sTG1OdmJRQUtDUkNuNml1a3JGQnEvTm5qQy80OWVUUTZZRnIwemF2VEZFc0lNU1owZHA2cwo4Y1dHVDhRdUdUbmd5MmQwc1BSQkdWVXpDVEdqcXRrOFkrTHR5eWFlb1hmU1J4RUJ4R0VnaWF1cTJvMjlzRXRDCnNUayszcXpCVTJUZ0RWR043ZWljRmxjZVpLVmEyL3BqdjdJWStzSjdvNEw0YmEyQW95ZkU0WmNWR1ZSZmVGamEKc2ttTHNKSFV6RGZNQlRSSEx6MDJpczV5RUdIeU1LWFRzVDZjWWJTV2wyNENJdzVSU0M1TytSTHNXSU5XV1czRQpkMnl3OElaK3QxYmZNRitSSzdUVmtJM1lTQTU3SWtJQzBJdTRmZmRSYi9vL085UWFqVHpzblpkU2sxUmtWY2huCjJvemp5QmIyS3V0aktMSEtRbXRMNjhaelRRZ2Rydjl2QStMeUNPNmgyeFB3em54bkNUOXBXNkZ2aDUwVTFIUlMKUm1mUU9kdXpEdHRINjl2ZSs1a2x3eDJLSDFLS1VxWU03N3Zwc1JhbllxYnE0b3pieEx2blJ0cWJOZGhWNDc5dQpYSGg2c3k3USt5Q0NjdzhlTE45MFdhZThqY1h1VzBrczhUeDhuZVhsaUJ4LzlKUWFWK1JOcXFvRFFFeTIvMytwCkhIVW1aT3ZkVkFmS3Ayb3hQa2VVaUNmTEhrc3cyMFVYcCtMN01qTT0KPUltaHMKLS0tLS1FTkQgUEdQIFNJR05BVFVSRS0tLS0tCg==
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
